### PR TITLE
Ka/snyk pr updates

### PR DESCRIPTION
**Pull request by kalagarraj**
Manually updated dependencies using snyk CLI. Review that

- depcheck is now a dev dependency
- .snyk has ignore rules for axios package (transitively dependent on yeoman)

Tests done
- ensured unit tests are passing
- created npm pack file using `npm pack`
- created commerce-app using `npx create-commerce-app-1.0.1.tgz test-app`
- ensured the `test-app\package.json` contains `test-app` as the name

### CODE REVIEW

**Review by dbarbato-sf — DISMISSED** [review]

**Review by gkhunger-sf — DISMISSED** [review]
This will take care of the axios issue for now. Is there anything we can do for the lodash issue?

**Comment by kalagarraj** [comment]
> This will take care of the axios issue for now. Is there anything we can do for the lodash issue?

is it taken care in this PR

**Review by shirishmaheshwari — DISMISSED** [review]
very well written description!

**Review by bredmond-sf — DISMISSED** [review]

**Comment by kalagarraj** [comment]
Closing and try reopening to check if snyk checks pass

**Review by bredmond-sf — DISMISSED** [review]

**Review by gkhunger-sf — DISMISSED** [review]

**Comment by kalagarraj** [comment]
closing to test snyk fixes

**Comment by kalagarraj** [comment]
Changes are taken care by PR#60

**Pull request closed without merging**
